/*
 * module function declaration for library ptrigmod header (autogenerated)
 */

#include "ptrigmod_module.h"

int ptrigmod_mod_init(ubx_node_info_t* ni)
{
  int ret;
  ret=ptrig_mod_init(ni);
  if(ret!=0)
    goto out;

out:
   return ret;
}

void ptrigmod_mod_cleanup(ubx_node_info_t* ni)
{
  ptrig_mod_cleanup(ni);
}

